apiVersion: v1
kind: Secret
metadata:
  name: acitypay-secrets
  namespace: acitypay-dev
type: Opaque
stringData:
  DB_USER: "acitypay"
  DB_PASSWORD: "acitypay_dev"

  KEYCLOAK_ADMIN_USER: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"

  MINIO_ROOT_USER: "acitypay"
  MINIO_ROOT_PASSWORD: "acitypay123"

  SFTP_PASSWORD: "bcppass"
